// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  profile: dynamic(() => import("./Profile")),
  rich_text: dynamic(() => import("./RichText")),
};
